catalogMode: prefer

shellEmulator: true

packages:
  - packages/**
  - plugins/**
  - services/**
  - examples/**
  - docs/**
  - apps/**
  - '!**/dist/**'

overrides:
  array-flatten: npm:@nolyfill/array-flatten@^1.0.44
  axios: npm:feaxios@^0.0.23
  is-core-module: npm:@nolyfill/is-core-module@^1.0.39
  isarray: npm:@nolyfill/isarray@^1.0.44
  safe-buffer: npm:@nolyfill/safe-buffer@^1.0.44
  safer-buffer: npm:@nolyfill/safer-buffer@^1.0.44
  side-channel: npm:@nolyfill/side-channel@^1.0.44
  string.prototype.matchall: npm:@nolyfill/string.prototype.matchall@^1.0.44

catalog:
  '@guiiai/logg': 1.1.0
  '@moeru/eslint-config': 0.1.0-beta.13
  '@moeru/std': 0.1.0-beta.13
  '@proj-airi/drizzle-duckdb-wasm': ^0.4.29
  '@xsai-ext/providers-cloud': ^0.4.0-beta.10
  '@xsai-ext/providers-local': ^0.4.0-beta.10
  '@xsai-ext/shared-providers': 0.4.0-beta.5
  '@xsai/embed': ^0.4.0-beta.10
  '@xsai/generate-speech': 0.4.0-beta.5
  '@xsai/generate-text': ^0.4.0-beta.10
  '@xsai/generate-transcription': ^0.4.0-beta.10
  '@xsai/model': ^0.4.0-beta.10
  '@xsai/shared': ^0.4.0-beta.10
  '@xsai/shared-chat': ^0.4.0-beta.10
  '@xsai/stream-text': ^0.4.0-beta.10
  '@xsai/tool': ^0.4.0-beta.10
  '@xsai/utils-chat': 0.4.0-beta.5
  electron-updater: ^6.6.2
  posthog-js: 1.306.1
  xsschema: ^0.4.0-beta.10

catalogs:
  rolldown-vite:
    vite: npm:rolldown-vite@^7.2.11

onlyBuiltDependencies:
  - '@discordjs/opus'
  - '@ffmpeg-installer/darwin-arm64'
  - '@parcel/watcher'
  - bufferutil
  - core-js
  - electron
  - electron-click-drag-plugin
  - es5-ext
  - esbuild
  - ffmpeg-static
  - msw
  - onnxruntime-node
  - protobufjs
  - sharp
  - simple-git-hooks
  - spawn-sync
  - utf-8-validate
  - vue-demi
